apiVersion: apps/v1 # api usada
kind: Deployment # tipo do resurso

metadata: #metadados do deployment
  name: frontend-deployment # nome para esse deployment
  labels: # labels para esse deployment
    app: frontend 

spec: # especificações desse deployment
  template: # dados do pod
    metadata:
      name: pod-my-nginx
      labels:
        env: production
    spec:
      containers:
        - name: nginx-container
          image: nginx:1.16.2
  
  selector: # selecionar o pod que vou usar nesse deployment
    matchLabels:
      env: production
  strategy:
    type: Recreate
  replicas: 5