apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: ClusterIP
  selector:
    type: web-app # selecionado o pod desse service
  ports:
    - name: http
      port: 80 # port no qual os pods externos se conectaram
      targetPort: 80 # port no qual será encaminhado a solicitação
    - name: http-tomcat
      port: 8080 # como não foi definido o targetPort, ele será automaticamente setado para 8080