apiVersion: v1
kind: Pod
metadata:
  name: web-pod
  labels:
    type: web-app
spec:
  containers: # os dois containers, o apache e o tomcat
    - name: web-server-apache
      image: httpd
      ports:
        - containerPort: 80
    - name: web-server-tomcat
      image: tomcat
      ports:
        - containerPort: 8080